#!/bin/sh
# ===========================================================================================
#  ______
# |   __ \.-----.-----.--.--.--.--------.----.----.
# |   __ <|__ --|  _  |  |  |  |        |   _|  __|
# |______/|_____|   __|________|__|__|__|__| |____|
#               |__|
# Description: The central configuration file for bspwm largely controls how the environment looks.
# Configure this to your liking, dear user.
# Author: Usergh0st
# Repository: https://github.com/Usergh0st/Machinepwn.git
# Mail: usergh0stmail@proton.me
# Last Update:  25.12.2025 4:11 PM
# Copyright (C) 2025-2026 Usergh0st <usergh0stmail@proton.me>
# Copyright (C) 2026-2027 Usergh0st <usergh0stmail@proton.me>
# ==========================================================================================

#  _______
# |    ___|.-----.--.--.
# |    ___||     |  |  |
# |_______||__|__|\___/

# -- Environment variables --
export _JAVA_AWT_WM_NONREPARENTING=1
export PATH="${HOME}/.config/bspwm/src:${PATH}"
export XDG_CURRENT_DESKTOP='bspwm'

#  ________              __
# |  |  |  |.-----.----.|  |--.-----.-----.---.-.----.-----.-----.
# |  |  |  ||  _  |   _||    <|__ --|  _  |  _  |  __|  -__|__ --|
# |________||_____|__|  |__|__|_____|   __|___._|____|_____|_____|
#                                   |__|

# -- Monitors --
# -- If you don't like the current resolution. --
# -- Replace [MonitorSetup.sh] with [CustomResolution.sh] and edit that's file. --
# -- If you want a custom resolution go to -> [~/.config/bspwm/src] edit that's file. --
# -- CustomResolution.sh --
MonitorSetup.sh

#  ______               ___ __
# |      |.-----.-----.'  _|__|.-----.
# |   ---||  _  |     |   _|  ||  _  |
# |______||_____|__|__|__| |__||___  |
#                              |_____|

# -- External Rules --
bspc config external_rules_command "${HOME}"/.config/bspwm/src/ExternalRules.sh

# -- Aesthetics --
bspc config border_width 2
bspc config window_gap 3
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

bspc config focused_border_color "#6f2524"
bspc config normal_border_color "#191f1a"
bspc config presel_feedback_color "#1d1918"

# -- General behavior --
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true
bspc config pointer_motion_interval 7
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# -- States --
bspc config automatic_scheme longest_side
bspc config split_ratio 0.50

# -- Layout --
bspc config initial_polarity second_child
bspc config removal_adjustment true

#  _______ __               __   __
# |     __|  |_.---.-.----.|  |_|__|.-----.-----.
# |__     |   _|  _  |   _||   _|  ||     |  _  |
# |_______|____|___._|__|  |____|__||__|__|___  |
#                                         |_____|

# -- Vmware Clip & Others --
wmname LG3D &>/dev/null &
vmware-user-suid-wrapper &>/dev/null &

# -- Launch The Polybars BarPwn And HomeBar --
# ~/.config/bspwm/homebar/launch.sh &
~/.config/bspwm/barpwn/launch.sh &

# -- Start sxhkd daemon hotkey --
pidof -q sxhkd || { sxhkd -c "${HOME}"/.config/bspwm/sxhkdrc & }

# -- Restore wallpaper with nitrogen --
# -- Remplaze with script in the future --
# -- I made the script but it's very simple --
# -- I made the script but it's very simple --
WallSelect.sh
