#!/usr/bin/env bash
#
#  __                                            
# |  |--.-----.-----.--.--.--.--------.----.----.
# |  _  |__ --|  _  |  |  |  |        |   _|  __|
# |_____|_____|   __|________|__|__|__|__| |____|
#	      |__|
#
#	Author		-	Usergh0st
#	Repository	-	https://github.com/Usergh0st/Machinepwn

# Bspwm monitors setup. 
bspc monitor -d 1 2 3 4 5 6 7

# Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

# Set environment variables
export PATH="$HOME/.config/bspwm/src:$PATH"

#                    ___ __        
# .----.-----.-----.'  _|__|.-----.
# |  __|  _  |     |   _|  ||  _  |
# |____|_____|__|__|__| |__||___  |
#			    |_____|
				    
bspc config window_gap          	5
bspc config split_ratio          	0.52
bspc config pointer_motion_interval   	7
bspc config removal_adjustment        	true
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config pointer_follows_focus 	true
bspc config gapless_monocle 		true
bspc config single_monocle            	true
bspc config focus_follows_pointer     	true
bspc config pointer_follows_focus     	false
bspc config pointer_follows_monitor   	true
bspc config automatic_scheme          	longest_side
bspc config initial_polarity          	second_child

bspc config pointer_modifier          	mod4
bspc config pointer_action1           	move
bspc config pointer_action2           	resize_side
bspc config pointer_action3           	resize_corner


#  _______ __               __   __              
# |     __|  |_.---.-.----.|  |_|__|.-----.-----.
# |__     |   _|  _  |   _||   _|  ||     |  _  |
# |_______|____|___._|__|  |____|__||__|__|___  |
#                                         |_____|
                                         
pidof -q sxhkd || { sxhkd -c "${HOME}"/.config/bspwm/sxhkdrc & }
